// DeepBench v7.0.549 | tests/regression/agt-86c-ledger-self-ingest.test.mjs | AGT-86 slice 3
//
// FEATURE: AGT-86 slice 3 -- the Auditor files its own findings, and the weekly report counts what
// was found. scripts/audit-ledger.js gains attribution() (exactly one of --cycle-id / --session-name,
// so a session can file without an open runner cycle), beforeImage() (the image carries only the
// attribution the ck_before_image_attribution CHECK demands), check_slug on toRow(), a dry-run line
// that says how many findings are waiting to be filed, and renderReport(week, rows, found) -- the
// report reads `<F> found, <L> filed` instead of `0 findings` when the candidates file holds work
// the ledger does not.
//
// FIVE ARMS (kickoff docs/kickoffs/v7.0.549-AGT-86-s3-ledger-self-ingest.md §6), each red on the
// tree before the change:
//   A  ATTRIBUTION (pure) -- both flags throw /exactly one/; --apply with neither throws; a session
//      name alone gives {cycle_id:null, session_name}; a dry run with neither gives two nulls.
//      Pre-change: attribution is not exported.
//   B  ROW SHAPE (pure) -- toRow passes check_slug through (null when absent) and leaves cycle_id
//      null on a session ingest; beforeImage carries exactly one non-null attribution.
//      Pre-change: beforeImage is not exported; toRow has no check_slug.
//   C  REPORT (pure) -- the found counts render and `0 findings` does not; the six-status ledger line
//      and the root-cause tickets line; CONTROL: the two-arg call over one open row byte-equals the
//      pinned legacy string (agt-70 part D's format holds). Pre-change: `0 findings`.
//   D  CLI REFUSALS (subprocess, env stripped of SUPABASE_*) -- both flags and --apply alone exit 2
//      naming /exactly one of --cycle-id / --session-name/, BEFORE the file is read or creds are
//      asked for. Pre-change: stderr is `SUPABASE_URL…` / `requires --cycle-id`.
//   E  LIVE (creds; notRun otherwise) -- a dry run of the fixture at 2026-W01 exits 1 saying
//      `1 new findings to file` and the ledger count is unchanged; --report=2026-W38 prints
//      `Found this run: 21 new + 4 carried` and never `0 findings`.
//
// The ledger is NEVER written: no arm passes --apply with a valid attribution, and E is a dry run.
// Every arm runs even when an earlier one fails; the test throws once at the end with every arm's
// failure, so one run reports the whole pre/post picture.

import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { spawnSync } from "node:child_process";
import { selfRun, notRun } from "./_lib/self-run.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const SCRIPT = path.join(ROOT, "scripts", "audit-ledger.js");
const CYCLE = "386e52e6-08ae-4bf6-ad3d-5944882fb8ff";
const ID = "00000000-0000-4000-8000-000000000086";

// The legacy header/section format agt-70 part D pins, for ONE open row, rendered by the two-arg call.
const LEGACY_ONE_OPEN = `<!-- GENERATED by scripts/audit-ledger.js --report=2026-W38 --write (AGT-70) from public.audit_findings — do not edit -->

# Audit 2026-W38 — 1 findings (1 open · 0 resolved · 0 not a defect)

## 0000000000000001 · contradiction · high · open

**Fact:** a fact

**Locations:**
- \`docs/a.md:1\` — "a"

**Proposed resolution:** fix it

First seen: 2026-W38 · found by hand:qa
`;

function row(fingerprint, status, extra = {}) {
  return {
    fingerprint, iso_week: "2026-W38", kind: "contradiction", confidence: "high", status,
    governing_fact: "a fact", locations: [{ location: "docs/a.md:1", text: "a" }],
    proposed_resolution: "fix it", ruling: null, ruled_by: null, ruled_at: null,
    found_by: "hand:qa", filed_backlog_id: null, ...extra,
  };
}

function runCli(args, env) {
  return spawnSync(process.execPath, [SCRIPT, ...args], { encoding: "utf8", cwd: ROOT, env });
}

async function run() {
  const failures = [];
  const arm = async (name, fn) => {
    try { await fn(); console.log(`    ok  ${name}`); }
    catch (e) { failures.push(`${name}: ${e.message.split("\n")[0]}`); console.log(`    FAIL ${name}: ${e.message.split("\n")[0]}`); }
  };

  const mod = await import(pathToFileURL(SCRIPT).href);
  const { attribution, beforeImage, toRow, renderReport } = mod;

  await arm("A attribution", () => {
    assert.equal(typeof attribution, "function", "attribution must be exported");
    assert.throws(() => attribution({ cycleId: CYCLE, sessionName: "s", apply: false }), /exactly one/);
    assert.throws(() => attribution({ cycleId: CYCLE, sessionName: "s", apply: true }), /exactly one/);
    assert.throws(() => attribution({ apply: true }), /exactly one/);
    assert.deepEqual(attribution({ sessionName: "s", apply: true }), { cycle_id: null, session_name: "s" });
    assert.deepEqual(attribution({ cycleId: CYCLE, apply: true }), { cycle_id: CYCLE, session_name: null });
    assert.deepEqual(attribution({ apply: false }), { cycle_id: null, session_name: null });
  });

  await arm("B row shape", () => {
    assert.equal(typeof beforeImage, "function", "beforeImage must be exported");
    const f = { kind: "contradiction", locations: [{ location: "docs/a.md:1", text: "a" }], governing_fact: "g",
      confidence: "high", proposed_resolution: "p", check_slug: "x" };
    const withSlug = toRow(f, { week: "2026-W38", foundBy: "hand:qa", sessionName: "s", id: ID });
    assert.equal(withSlug.check_slug, "x", "check_slug passes through");
    assert.equal(withSlug.cycle_id, null, "a session ingest leaves cycle_id null");
    const { check_slug: _drop, ...noSlug } = f;
    assert.equal(toRow(noSlug, { week: "2026-W38", foundBy: "hand:qa", cycleId: CYCLE, id: ID }).check_slug, null,
      "a finding without check_slug files null");
    const bs = beforeImage({ sessionName: "s", id: ID });
    assert.deepEqual(bs, { cycle_id: null, session_name: "s", table_name: "audit_findings", pk_value: ID, row_data: null });
    const bc = beforeImage({ cycleId: CYCLE, id: ID });
    assert.equal(bc.session_name, null);
    assert.equal(bc.cycle_id, CYCLE);
    // CONTROL: exactly one attribution non-null in each (the CHECK's own rule).
    for (const b of [bs, bc]) {
      assert.equal([b.cycle_id, b.session_name].filter(v => v != null).length, 1, "exactly one attribution");
    }
  });

  await arm("C report", () => {
    const empty = renderReport("2026-W38", [], { new: 21, carried: 4 });
    assert.ok(empty.includes("25 found, 0 filed yet"), `header must count found; got: ${empty.split("\n")[2]}`);
    assert.ok(empty.includes("Found this run: 21 new + 4 carried (docs/audits/2026-W38-candidates.json)"));
    assert.ok(!empty.includes("0 findings"), "the report must not read `0 findings` when work was found");

    const six = [
      row("0000000000000001", "open"),
      row("0000000000000002", "ticketed", { filed_backlog_id: "AGT-91" }),
      row("0000000000000003", "ticketed", { filed_backlog_id: "AGT-90" }),
      row("0000000000000004", "carried"),
      row("0000000000000005", "escalated"),
      row("0000000000000006", "not-a-defect"),
    ];
    const r6 = renderReport("2026-W38", six);
    assert.ok(r6.includes("# Audit 2026-W38 — 6 found, 6 filed\n"), `six-row header; got: ${r6.split("\n")[2]}`);
    assert.ok(r6.includes("Ledger: 1 open · 2 ticketed · 1 carried · 1 escalated · 1 not-a-defect · 0 resolved"));
    assert.ok(r6.includes("Root-cause tickets: AGT-90, AGT-91"));
    assert.ok(r6.includes("**Ticket:** AGT-90"), "a ticketed section names its ticket");
    assert.ok(!r6.includes("Found this run:"), "no found line without a candidates count");

    // CONTROL: the legacy two-arg call over one open row is byte-identical to today's format.
    assert.strictEqual(renderReport("2026-W38", [row("0000000000000001", "open")]), LEGACY_ONE_OPEN);
  });

  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "agt-86c-"));
  const fixture = path.join(tmp, "fixture.json");
  fs.writeFileSync(fixture, JSON.stringify({
    week: "2026-W01", found_by: "hand:agt-86c-qa",
    findings: [{
      kind: "contradiction", confidence: "low", proposed_resolution: "none -- a QA fixture, never filed",
      governing_fact: `agt-86c-qa ${Date.now()}`,
      locations: [{ location: `tests/regression/agt-86c-fixture-${Date.now()}.md:1`, text: "fixture" }],
    }],
  }));

  await arm("D CLI refusals", () => {
    const env = { ...process.env };
    for (const k of Object.keys(env)) if (k.startsWith("SUPABASE_")) delete env[k];
    const re = /exactly one of --cycle-id \/ --session-name/;
    const both = runCli([`--ingest=${fixture}`, "--week=2026-W01", "--apply", `--cycle-id=${CYCLE}`, "--session-name=x"], env);
    assert.equal(both.status, 2, `both flags must exit 2; got ${both.status}: ${both.stderr.trim()}`);
    assert.match(both.stderr, re, `both flags stderr; got: ${both.stderr.trim()}`);
    const neither = runCli([`--ingest=${fixture}`, "--week=2026-W01", "--apply"], env);
    assert.equal(neither.status, 2, `--apply alone must exit 2; got ${neither.status}`);
    assert.match(neither.stderr, re, `--apply alone stderr; got: ${neither.stderr.trim()}`);
    const src = fs.readFileSync(SCRIPT, "utf8").split("\n").slice(0, 140).join("\n");
    assert.ok(src.includes("--session-name=<name>"), "the Usage header names --session-name=<name>");
  });

  const url = (process.env.SUPABASE_URL ?? "").replace(/\/+$/, "");
  const key = process.env.SUPABASE_SERVICE_KEY ?? "";
  if (!url || !key) {
    notRun("AGT-86c live arm (E)",
      "SUPABASE_URL + SUPABASE_SERVICE_KEY absent -- the dry-run line and the W38 found counts are unverified here. Run: node --env-file=.env.local tests/regression/agt-86c-ledger-self-ingest.test.mjs");
  } else {
    await arm("E live", async () => {
      const count = async () => {
        const res = await fetch(`${url}/rest/v1/audit_findings?select=id`, { headers: { apikey: key, Authorization: `Bearer ${key}` } });
        if (!res.ok) throw new Error(`count read HTTP ${res.status}`);
        return (await res.json()).length;
      };
      const before = await count();
      const dry = runCli([`--ingest=${fixture}`, "--week=2026-W01"], process.env);
      assert.equal(dry.status, 1, `dry run with one new finding must exit 1; got ${dry.status}: ${dry.stderr.trim()}`);
      assert.match(dry.stderr, /1 new findings to file/, `dry-run stderr; got: ${dry.stderr.trim()}`);
      const after = await count();
      assert.equal(after, before, `the ledger must not move: ${before} -> ${after}`);
      const rep = runCli(["--report=2026-W38"], process.env);
      assert.equal(rep.status, 0, `report must exit 0; got ${rep.status}: ${rep.stderr.trim()}`);
      assert.ok(rep.stdout.includes("Found this run: 21 new + 4 carried"), `report stdout; got: ${rep.stdout.split("\n").slice(0, 6).join(" | ")}`);
      assert.ok(!rep.stdout.includes("0 findings"), "the W38 report must not read `0 findings`");
    });
  }

  fs.rmSync(tmp, { recursive: true, force: true });
  if (failures.length) throw new Error(`${failures.length} arm(s) failed:\n      ${failures.join("\n      ")}`);
}

selfRun(import.meta.url, run);
export default run;
