// DeepBench v7.0.622 | tests/regression/agt-174-state-render-self.test.mjs | AGT-174 — THE STATE RENDER
// NAMES ITS OWN SHIP, AND SAYING SO NEVER BECOMES A REFUSAL.
//
// THE DEFECT THIS GUARDS, measured on the tree AGT-174 shipped from rather than reasoned about:
// `scripts/render-claude-state.js` selects the ledger with `push_sha=not.is.null` and takes no cycle
// argument, so a close-out that renders BEFORE writing its own `push_sha` to `runner_cycles` renders a
// ledger it is not in. `git show 034876e5~1:CLAUDE-STATE.md` line 4 names v7.0.619 / `3c489041` while
// the cycle that wrote and pushed it was `f4e24696` (v7.0.618) — a correct render of a stale ledger,
// publishing its predecessor's ship. `034876e5` names its own ship only because `ef3ef208` happened to
// write `push_sha` first. The runbook already states the order (runner-cycle.md:2928-2929, :3253-3254);
// nothing NOTICED when it was missed.
//
// THREE ARMS, and what each proves is stated rather than implied:
//
//   1. THE FINDING, on fixture pins whose first id is known (always runs, no network, no tree write).
//      All of `renderingCycleFinding`'s outcomes, including the two that must return null, and the
//      lag / not-lag distinction — a pin the cycle is ABSENT from is the defect above and carries the
//      remedy; a pin it sits at position 2 of is a peer pushing after it (B42), expected and not a
//      lag. A test that only asserted "returns something" would pass a function that reported the
//      concurrency case as the bug, which is the discrimination that matters here (the LOO-013
//      lesson: assert WHICH branch fired).
//   2. NON-GATING, on scripts/verifier.js's own source (always runs). The renderer has exactly ONE
//      deliberate exit 2 — a body that lost the standing-brief link, John's fail-closed condition on
//      gated card 37b22393 — and a second way to refuse, in either file, would wedge every close-out
//      on the platform behind a lag the cycle cannot fix from inside its own render. WITH ITS OWN
//      POSITIVE CONTROL, which is what stops this arm going vacuously green: the SAME two patterns
//      must MATCH inside the `kickoffNoLanes` block, which really does block, and must NOT match after
//      `let stateRenderCycle`. They are asserted SEPARATELY rather than as one alternation, because an
//      alternation hides a typo in either half behind the other — measured, not assumed, on this
//      test's own first run. A typo'd or over-narrow pattern now fails its control before it can pass
//      the claim.
//   3. BOTH JUDGE LANES carry the evidence key (always runs). SES-337's lesson, and
//      ses-345-verdict-graded-sha.test.mjs already anchors the two-literal count: the same key
//      carrying less content in one lane than the other is a lane-shaped difference in the ledger.
//
// WHAT THIS DOES NOT ASSERT, and must not: nothing about whether CLAUDE-STATE.md on disk is currently
// in lag. That is a fact about the live world at one instant, not about this change (pattern:162 — a
// check grades the change, never the live world), and SES-177 / SES-261 already own the committed
// file. This suite must stay runnable with no credentials and with no ledger read at all.
//
// Invocation: node tests/regression/agt-174-state-render-self.test.mjs
// (STANDARDS.md Section 2 rule 5 for the credentialed form; this test needs no credentials.)

import assert from "assert";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { selfRun } from "./_lib/self-run.js";
import { renderingCycleFinding } from "../../scripts/render-claude-state.js";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const VERIFIER_REL = "scripts/verifier.js";

// Real cycle ids from this ticket's own measurement, so the fixture is a real shape rather than a
// convenient one: the AGT-174 cycle, the `034876e5` ship's cycle, and the lagging `f4e24696`.
const SELF = "25885076-9201-46de-a945-3c7210e5acb6";
const PEER = "ef3ef208-0000-4000-8000-000000000001";
const OLDER = "f4e24696-0000-4000-8000-000000000002";

// The pin lives in the file's trailing generated marker; `parsePin` reads exactly this shape.
const fileWithPin = ids =>
  "# DeepBench — Current State\n\n**Version in dev:** v7.0.621\n\n" +
  `<!-- generated by scripts/render-claude-state.js — do not hand-edit. ledger-pin: ${ids.join(",")} -->\n`;

// --- arm 1: the finding ------------------------------------------------------------------------

function noCycleIdIsNotMeasuredRatherThanClean() {
  // A caller with no cycle id cannot know, and inventing "clean" here is the vacuous pass this
  // whole ticket is about. The distinction is carried in the CALLER's words (verifier's prose line),
  // so what this function owes is null — not a finding claiming the file is fine.
  assert.strictEqual(renderingCycleFinding(fileWithPin([SELF]), null), null);
  assert.strictEqual(renderingCycleFinding(fileWithPin([SELF]), ""), null);
  assert.strictEqual(renderingCycleFinding(fileWithPin([SELF]), undefined), null);
}

function thePinTopBeingThisCycleIsTheCleanCase() {
  assert.strictEqual(renderingCycleFinding(fileWithPin([SELF, PEER, OLDER]), SELF), null,
    "a file whose newest pinned row IS this cycle published this cycle's ship — nothing to report");
}

function absentFromThePinIsTheLagAndCarriesTheRemedy() {
  const f = renderingCycleFinding(fileWithPin([PEER, OLDER]), SELF);
  assert.ok(f, "a render that does not contain this cycle at all IS the AGT-174 lag — it must report");
  assert.strictEqual(f.kind, "state-render-not-self");
  assert.strictEqual(f.lag, true, "absent from the pin is a LAG, not the concurrency case");
  assert.strictEqual(f.pin_index, -1);
  assert.strictEqual(f.pin_top, PEER, "pin_top must be the row the file actually published");
  assert.match(f.reason, /push_sha/,
    "the reason must name the remedy — write push_sha (and version) to the cycle row, then re-render — " +
    "not merely announce the lag");
  assert.match(f.reason, /previous ship|PREVIOUS ship/i);
  // The remedy names the re-render, so a reader who has never seen this ticket can act on the line
  // alone. pattern:155 — a report that says it stopped is not a report.
  assert.match(f.reason, /re-render/);
}

function presentButNotFirstIsThePeerPushAndIsNotALag() {
  const f = renderingCycleFinding(fileWithPin([PEER, SELF, OLDER]), SELF);
  assert.ok(f, "not being the newest pinned row is still worth reporting — a reader must not guess");
  assert.strictEqual(f.kind, "state-render-not-self");
  assert.strictEqual(f.lag, false,
    "a peer pushing AFTER this render is expected under 5-7 concurrent sessions (B42); reporting it " +
    "as the lag above would send its reader to fix a cycle row that is already correct");
  assert.strictEqual(f.pin_index, 1);
  assert.strictEqual(f.pin_top, PEER);
  // THE DISCRIMINATION, stated as its own assertion: the two non-null cases must not read alike.
  const lagged = renderingCycleFinding(fileWithPin([PEER, OLDER]), SELF);
  assert.notStrictEqual(f.reason, lagged.reason);
  assert.notStrictEqual(f.lag, lagged.lag);
}

function anUnparseablePinIsReportedAndNeverSilentlyClean() {
  // `parsePin` returns [] for a hand-edited or pre-SES-261 file. Its own header insists that must
  // never mean a pass, and the same rule applies here: a stripped pin cannot be shown to publish
  // this cycle, so it reports, with lag true and the same remedy.
  for (const text of ["", "no marker here at all\n", "# state\n<!-- generated, pin removed -->\n"]) {
    const f = renderingCycleFinding(text, SELF);
    assert.ok(f, `a file with no readable ledger-pin must report, not pass: ${JSON.stringify(text)}`);
    assert.strictEqual(f.kind, "state-render-no-pin");
    assert.strictEqual(f.lag, true);
    assert.strictEqual(f.pin_index, -1);
    assert.strictEqual(f.pin_top, null);
    assert.match(f.reason, /push_sha/);
  }
}

// --- arm 2: non-gating, with its own positive control -------------------------------------------

// The two blocks are read the same way from the same source, so the comparison is between them
// rather than against a hand-copied expectation.
const blockAfter = (src, decl, lines = 15) => {
  const i = src.indexOf(decl);
  assert.notStrictEqual(i, -1, `${VERIFIER_REL} must still declare \`${decl}\``);
  return src.slice(i).split("\n").slice(0, lines).join("\n");
};

// TWO PATTERNS, ASSERTED SEPARATELY, NOT ONE ALTERNATION — and the difference is not cosmetic. With
// `/verdict\s*=|reasoning\s*=/` as a single regex, mistyping ONE half still matches the positive
// control through the other, so the control cannot catch it; measured on this test's first run
// (`verdcit` passed). Each half therefore carries its own control: a typo in either one fails there
// before it can pass the claim.
const GATING = [
  { name: "verdict assignment", re: /verdict\s*=/ },
  { name: "reasoning assignment", re: /reasoning\s*=/ },
];

function theFindingNeverTouchesTheVerdict() {
  const src = fs.readFileSync(path.join(REPO, VERIFIER_REL), "utf8").replace(/\r\n/g, "\n");
  const gating = blockAfter(src, "let kickoffNoLanes = null;");
  const reporting = blockAfter(src, "let stateRenderCycle = null;");

  for (const { name, re } of GATING) {
    // POSITIVE CONTROL FIRST. `kickoffNoLanes` is a block that really does turn approve into block,
    // so this pattern MUST match there. If it does not, the pattern is wrong and the claim below
    // would be vacuous — this assertion is what makes the negative one mean something.
    assert.match(gating, re,
      `positive control failed for the ${name} pattern: the kickoffNoLanes block DOES assign the ` +
      "mechanical lane's verdict and reasoning, so this pattern must match it. A pattern that misses " +
      "it would pass the claim below on any source at all.");

    // THE CLAIM. AGT-174 is reported, never enforced: a second refusal path beside the renderer's one
    // deliberate exit 2 (the standing-brief link, gated card 37b22393) would wedge every close-out.
    assert.doesNotMatch(reporting, re,
      `the AGT-174 block must NOT assign the mechanical lane's ${name} — the check warns and the ` +
      "render is still written. See the block's own header in " + VERIFIER_REL);
  }

  // And it is wired at all: an import that nothing calls would satisfy the line above trivially.
  assert.match(src, /import \{ renderingCycleFinding \} from "\.\/render-claude-state\.js";/,
    `${VERIFIER_REL} must import the renderer's pure helper rather than restate the predicate`);
  assert.match(src, /stateRenderCycle = renderingCycleFinding\(/,
    `${VERIFIER_REL} must actually call renderingCycleFinding()`);
  assert.match(src, /CLAUDE-STATE: \$\{stateRenderCycle/,
    `${VERIFIER_REL}'s prose must print the finding on every run, gating or not`);
  assert.match(src, /not measured \(no --cycle-id\)/,
    `${VERIFIER_REL} must say "not measured" when no cycle id was passed — never report it as clean`);
}

// --- arm 3: both judge lanes --------------------------------------------------------------------

function bothJudgeLanesSeeTheSameEvidence() {
  const src = fs.readFileSync(path.join(REPO, VERIFIER_REL), "utf8").replace(/\r\n/g, "\n");
  const literals = src.split(/const judgeCtx = \{/).slice(1);
  assert.strictEqual(literals.length, 2,
    `${VERIFIER_REL} must still have exactly two judgeCtx literals (session and executor). ` +
    `got: ${literals.length}`);
  for (const [i, block] of literals.entries()) {
    assert.match(block.slice(0, 4000), /state_render_cycle:/,
      `judgeCtx literal ${i + 1} must carry state_render_cycle: — the same evidence key in BOTH lanes, ` +
      "or one judge grades with a fact the other never sees (this file's SES-337 lesson)");
  }
  assert.match(src, /state_render_cycle: stateRenderCycle,/,
    "the --json payload must report the finding (reported, never its own runner_verdicts column — " +
    "AGT-170's convention, no migration)");
}

async function run(/* ctx */) {
  const results = [];

  noCycleIdIsNotMeasuredRatherThanClean();
  thePinTopBeingThisCycleIsTheCleanCase();
  absentFromThePinIsTheLagAndCarriesTheRemedy();
  presentButNotFirstIsThePeerPushAndIsNotALag();
  anUnparseablePinIsReportedAndNeverSilentlyClean();
  results.push("finding-all-branches-lag-vs-peer-discriminated");

  theFindingNeverTouchesTheVerdict();
  results.push("non-gating-with-kickoffNoLanes-positive-control");

  bothJudgeLanesSeeTheSameEvidence();
  results.push("both-judge-lanes-and-json-carry-state_render_cycle");

  return results;
}

selfRun(import.meta.url, run);
export default run;
